<?php
    /*
    Plugin Name: Remove Current Menu Link
    Plugin URI: Does not exist yet
    Description: Removes link to the current item from a menu generated by wp_list_pages and wp_list_categories. This makes a WordPress website or blog comply with the usability guidelines that a web page should not have a link to itself.
    Version: 1.0
    Author: Bill Stoddard
    Author URI: http://clockinfo.com/
    */

    /* Copyright 2007 Bill Stoddard (email : bill@billsclockworks.com)

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
    */

    /**************************************

    Hooks and configuration

    ***************************************/
    add_filter('wp_list_pages','list_pages_filter');
    add_action('wp_list_categories', 'list_categories_filter');

    function list_pages_filter($content) {
    /* for some reason it would not work with [:blank:]* after the m in current_page_item */
    return eregi_replace('(current_page_item"><a [^<]*href=["|\']?([^ "\']*)["|\']?[^>]*>([^<]*)</a>)','current_page_item">\\3', $content);
    }

    function list_categories_filter($content) {
    return eregi_replace('(current-cat[:blank:]*"><a [^<]*href=["|\']?([^ "\']*)["|\']?[^>]*>([^<]*)</a>)','">\\3', $content);
    }

    ?>